"""
SupplyChain Copilot MCP Server (stdio).

Exposes policy RAG + KPI NL2SQL as MCP tools so the Copilot LangGraph agent
acts as an MCP client (list_tools → call_tool) instead of hard-coded imports.

Run standalone:
  python -m mcp_server.server
"""

from __future__ import annotations

import os
import sys

# Stdio transport owns stdout for JSON-RPC. Force project prints/logs to stderr
# before any project imports that might write to stdout.
os.environ.setdefault("MCP_STDIO_MODE", "1")
if hasattr(sys.stdout, "reconfigure"):
    pass  # keep binary-safe defaults from the MCP SDK


def _ensure_stderr_logging() -> None:
    import logging

    root = logging.getLogger()
    if not root.handlers:
        logging.basicConfig(level=logging.WARNING, stream=sys.stderr)


_ensure_stderr_logging()

from mcp.server.fastmcp import FastMCP
from mcp.server.fastmcp.exceptions import ToolError

from mcp_server.tools import (
    ToolValidationError,
    dumps_tool_result,
    query_kpi_impl,
    query_policy_impl,
    score_supplier_risk_impl,
)

mcp = FastMCP(
    "supplychain-copilot-tools",
    instructions=(
        "Tools for the Ratti Supplier Lifecycle Copilot. "
        "Use query_policy for policy/process/document questions; "
        "Use query_kpi for numeric supplier performance metrics; "
        "use score_supplier_risk as the single risk-scoring contract "
        "(assessment, chat, and MCP all share this implementation)."
    ),
)


@mcp.tool(
    name="query_policy",
    description=(
        "Retrieve supplier-lifecycle policy evidence via hybrid RAG (Pinecone + BM25). "
        "Use when the user asks what a policy/SOP/contract/FAQ SAYS — e.g. Kraljic monitoring "
        "rules, ESG formula, pre-qualification vs qualification, audit policy, document "
        "requirements. Returns retrieved document chunks and a concatenated context string. "
        "Do NOT use for numeric KPIs (OTD, defect rate, spend) — use query_kpi instead."
    ),
)
def query_policy(query: str, k: int = 5) -> str:
    """RAG retrieval over policy/contract/sop/faq corpora."""
    try:
        result = query_policy_impl(query=query, k=k)
    except ToolValidationError as exc:
        raise ToolError(str(exc)) from exc
    except Exception as exc:
        raise ToolError(f"query_policy failed: {exc}") from exc
    return dumps_tool_result(result)


@mcp.tool(
    name="query_kpi",
    description=(
        "Query supplier KPI / performance metrics from the demo SQLite warehouse "
        "(deterministic SQL templates + read-only allowlisted SQL). "
        "Use when the user wants numbers: on-time delivery (OTD), defect rate, spend, "
        "average delay days, ESG score, vendor rating, certificate expiry, or supplier "
        "status/next step for a SUP### id. "
        "Arguments: supplier_id (optional SUP###), metric (on_time_rate|defect_rate|"
        "avg_delay_days|spend|esg_score|vendor_rating|cert_expiry|supplier_status), "
        "time_range (e.g. 2025, last_3_months). Optional question helps template matching. "
        "Optional sql: pass a SELECT generated by NL2SQL fallback. "
        "Invalid params return a standard MCP tool error — do not invent a parallel error schema. "
        "Do NOT use for pure policy text questions — use query_policy instead."
    ),
)
def query_kpi(
    supplier_id: str = "",
    metric: str = "",
    time_range: str = "",
    question: str = "",
    sql: str = "",
) -> str:
    """NL2SQL / templated KPI query against demo SQLite."""
    try:
        result = query_kpi_impl(
            supplier_id=supplier_id,
            metric=metric,
            time_range=time_range,
            question=question,
            sql=sql,
        )
    except ToolValidationError as exc:
        raise ToolError(str(exc)) from exc
    except Exception as exc:
        raise ToolError(f"query_kpi failed: {exc}") from exc
    return dumps_tool_result(result)


@mcp.tool(
    name="score_supplier_risk",
    description=(
        "Score supplier risk 0–100 from risk_events, quality_events, and document expiry. "
        "Canonical risk contract: assessment, chat, and MCP must reuse this tool so scores stay consistent. "
        "Returns risk_score, band (low|medium|high), drivers, component breakdown, and event rows."
    ),
)
def score_supplier_risk(supplier_id: str, as_of_date: str = "") -> str:
    """Weighted supplier risk score from demo SQLite signals."""
    try:
        result = score_supplier_risk_impl(supplier_id=supplier_id, as_of_date=as_of_date)
    except ToolValidationError as exc:
        raise ToolError(str(exc)) from exc
    except Exception as exc:
        raise ToolError(f"score_supplier_risk failed: {exc}") from exc
    return dumps_tool_result(result)


def main() -> None:
    # Default transport = stdio (client spawns this process).
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
